# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b489e816ee61c9535efa8bc42f4115e6e09d707f068e2cade4f96eb440fb6820d8736456e5d99e78a6de56fd2a16349df4cf66e87f14110bf95a432665afbc8f

test:
  secret_key_base: 817c568c01c0e1529d81d13a23eb1e06bcc47c5f8796a9ebdca432bcccb0604205a55e09f489ab33bcd5143e1255d316f457761b119a2753001dfa5e325c256b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
